nohup krenew -t -K 10 -- bash -c "python NLLPlot.py --process ttZ_3l --selection lepSel3-onZ-njet3p-nbjet1p-Zpt0-leptonIso3 --sample fwlite_ttZ_ll_LO_order2_15weights_ref --level reco --version approval --variables ctZ ctZI --zRange 0 40 --luminosity 3000 --binning 31 -1.1 1.1 31 -1.1 1.1 --smooth --contours --cores 3  --binMultiplier 5 --scale14TeV --detector phase2_CMS --addNonPrompt --useCombine" &
#nohup krenew -t -K 10 -- bash -c "python NLLPlot.py --process ttZ_3l --selection lepSel3-onZ-njet3p-nbjet1p-Zpt0-leptonIso3 --sample fwlite_ttZ_ll_LO_order2_15weights_ref --level reco --version approval --variables cpQM cpt --zRange 0 40 --luminosity 3000 --binning 31 -5 10 31 -5 10 --smooth --contours --cores 6  --binMultiplier 5 --scale14TeV --detector phase2_CMS --addNonPrompt --useCombine" &
nohup krenew -t -K 10 -- bash -c "python NLLPlot.py --process ttZ_3l --selection lepSel3-onZ-njet3p-nbjet1p-Zpt0-leptonIso3 --sample fwlite_ttZ_ll_LO_order2_15weights_ref --level reco --version approval --variables cpQM cpt --zRange 0 40 --luminosity 3000 --binning 51 -5 10 51 -5 10 --smooth --contours --cores 6  --binMultiplier 5 --scale14TeV --detector phase2_CMS --addNonPrompt --useCombine" &

nohup krenew -t -K 10 -- bash -c "python NLLPlot.py --process ttZ_3l --selection lepSel3-onZ-njet3p-nbjet1p-Zpt0-leptonIso3 --sample fwlite_ttZ_ll_LO_order2_15weights_ref --level reco --version approval --variables ctZ ctZI --zRange 0 40 --luminosity 3000 --binning 31 -1.1 1.1 31 -1.1 1.1 --smooth --contours --cores 3  --binMultiplier 5 --scale14TeV --detector phase2_CMS --addNonPrompt --useCombine --statOnly" &
nohup krenew -t -K 10 -- bash -c "python NLLPlot.py --process ttZ_3l --selection lepSel3-onZ-njet3p-nbjet1p-Zpt0-leptonIso3 --sample fwlite_ttZ_ll_LO_order2_15weights_ref --level reco --version approval --variables cpQM cpt --zRange 0 40 --luminosity 3000 --binning 51 -5 10 51 -5 10 --smooth --contours --cores 3  --binMultiplier 5 --scale14TeV --detector phase2_CMS --addNonPrompt --useCombine --statOnly" &

nohup krenew -t -K 10 -- bash -c "python NLLPlot.py --process ttZ_3l --selection lepSel3-onZ-njet3p-nbjet1p-Zpt0-leptonIso3 --sample fwlite_ttZ_ll_LO_order2_15weights_ref --level reco --version approval --variables ctZ ctZI --zRange 0 40 --luminosity 3000 --binning 31 -1.1 1.1 31 -1.1 1.1 --smooth --contours --cores 3  --binMultiplier 5 --scale14TeV --detector phase2_CMS --addNonPrompt --useCombine --noExpUnc" &
nohup krenew -t -K 10 -- bash -c "python NLLPlot.py --process ttZ_3l --selection lepSel3-onZ-njet3p-nbjet1p-Zpt0-leptonIso3 --sample fwlite_ttZ_ll_LO_order2_15weights_ref --level reco --version approval --variables cpQM cpt --zRange 0 40 --luminosity 3000 --binning 51 -5 10 51 -5 10 --smooth --contours --cores 6  --binMultiplier 5 --scale14TeV --detector phase2_CMS --addNonPrompt --useCombine --noExpUnc" &

